### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by cmutel** [michaelweinold/bw_hybrid#15]
Library and repo names are different (`bw2hybrid` versus `brightway2-hybridization`); moreover this library should **not** be compatible with Brightway 2, but the "next generation", partially available already. Therefore, I suggest that we change both repo and library names to either `bw_hybridization`, `bw_hybrid`, or `bw_heuristic_hybridization`.

**Comment by michaelweinold** [comment]
Repo and relevant directories renamed to `bw_hybrid` with https://github.com/michaelweinold/bw_hybrid/commit/e755cdb1152fb9c75d4089de54d036e4b39bc541.
