### ISSUE TITLE
Notebook `1_pylcaio_to_brightway.ipynb` doesn't include complete dependencies

### ISSUE THREAD

**Issue by cmutel** [michaelweinold/bw_hybrid#40]
Libraries `pymrio` and `ecospold2matrix` not installed in indicated [environment file](https://github.com/michaelweinold/config_conda/blob/main/bw_import_ei38.yml).

**Comment by michaelweinold** [comment]
Apologies, link meant to direct [at this environment file](https://github.com/michaelweinold/config_conda/blob/main/pylcaio_ecoinvent_3_8.yml).
